events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

        root /usr/share/nginx/html;
        index index.html;

        # Correct MIME types for JS modules, etc.
        types {
            text/javascript js mjs;
            application/wasm wasm;
        }

        location / {
            try_files $uri /index.html;
        }
    }
}
