services:
  backend:
    container_name: 'backend'
    image: 'ghcr.io/imrancse94/chat-application-backend:latest'
    ports:
      - "8000:8000"
    networks:
      - chat-network
    restart: always  
    
networks:
  chat-network:
    driver: bridge

