services:
  backend:
    container_name: 'backend'
    image: '${BACKEND_IMAGE}'
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - chat-network
    restart: always  

  mongo:
    container_name: 'db'
    image: mongo:latest
    volumes:
      - ./docker/mongodb:/data/db
    networks:
      - chat-network
    restart: always

  redis:
    container_name: 'redis'
    image: redis
    ports:
      - "27017:27017"
    networks:
      - chat-network
    restart: always

  worker:
    container_name: 'worker'
    image: '${BACKEND_IMAGE}'
    env_file:
      - .env
    command: ["node", "worker.js"]
    depends_on:
      - mongo
      - redis
    networks:
      - chat-network
    
networks:
  chat-network:
    driver: bridge

