services:
  backend:
    container_name: 'backend'
    image: '${BACKEND_IMAGE}'
    ports:
      - "8000:8000"
    networks:
      - chat-network
    restart: always  
    
networks:
  chat-network:
    driver: bridge

